### ISSUE TITLE
Support for Aeson 2.0

### ISSUE THREAD

**Issue by alexbiehl** [launchdarkly/haskell-server-sdk#35]
Aeson 2.0 introduced the `Key` and `KeyMap` abstractions to guard against hash explosions when dealing with JSON from external sources which breaks backward compatibility with older Aeson versions. 

It looks like this codebase uses Aeson in non-standard way and directly manipulates object which makes supporting Aeson 2.0 non-trivial.

**Comment by louis-launchdarkly** [comment]
Hello @alexbiehl, thank you for bringing this issue to our attention. We will discuss what to do internally and get back to you once we have the next step.

**Comment by alexbiehl** [comment]
@louis-launchdarkly Are there any news on this?

**Comment by keelerm84** [comment]
This has been released in 3.0.1
