### ISSUE TITLE
CircleCI run-quality-checks failing to build hpack

### ISSUE THREAD

**Issue by bmillwood** [launchdarkly/haskell-server-sdk#60]
It looks like CircleCI run-quality-checks has been failing lately due to a failure building connection-0.2.5 which is a dependency of hpack-0.35.1.

Mainly opening this issue to let you know that the Hackage metadata for connection-0.2.5 has been updated to fix the build (see https://github.com/vincenthz/hs-connection/issues/54), so just rerunning may be sufficient. If it's not, it might be a prompt to update hpack versions?

**Comment by keelerm84** [comment]
Thank you for the report. I will look into this more and see if we can get it resolved. Thanks!

**Comment by keelerm84** [comment]
You were right that a re-build fixed that issue. I had to make a small tweak to the way we install hlint, but circleci seems to be passing now.

Thank you again for you report. Have a great week!
